### ISSUE TITLE
minting table not removing utxo from "red" after it finds a new block and becomes "blue"

### ISSUE THREAD

**Issue by mh001** [Peerunity/Peerunity#177]
After a red unspent output finds a POS block, it becomes blue in the minting table in the client. The problem is that I see an utxo that found a block yesterday still having a red entry in addition to a blue one, as if  it hasn't found a block. I think the red entry should be rremoved.

**Comment by glv2** [comment]
Which version of peerunity are you using? A released binary, or a version you compiled yourself?

There is a fix for this problem in the master branch (commit a05317436e5c5570e7a52ef274b3acc543f7e681), but it is not yet in any release binary.

So please tell us if you saw the problem using a version you compiled yourself from the current master branch, because this would indicate that the fix needs to be improved...

**Comment by mh001** [comment]
Sorry for taking so long to get back. I am using standard win 32bit v0.1.2-RC1. So all needed to be done is waiting the standard release to update.
